from __future__ import annotations

from enum import StrEnum

__version__ = "1.1.1"
SCHEMA_VERSION = "1.0"
STATE_DIR = ".stackmarshal"


class Mode(StrEnum):
    RESEARCH = "research"
    PREPARE = "prepare"
    BUILD = "build"
    RESUME = "resume"


class Phase(StrEnum):
    INVOCATION_CHECK = "INVOCATION_CHECK"
    INTENT_NORMALIZATION = "INTENT_NORMALIZATION"
    ENVIRONMENT_AUDIT = "ENVIRONMENT_AUDIT"
    RESEARCH_GATE = "RESEARCH_GATE"
    LANDSCAPE_RESEARCH = "LANDSCAPE_RESEARCH"
    CAPABILITY_MAPPING = "CAPABILITY_MAPPING"
    CAPABILITY_DISCOVERY = "CAPABILITY_DISCOVERY"
    TRUST_EVALUATION = "TRUST_EVALUATION"
    ISOLATED_POC = "ISOLATED_POC"
    ARCHITECTURE_FREEZE = "ARCHITECTURE_FREEZE"
    TASK_GRAPH = "TASK_GRAPH"
    IMPLEMENTATION = "IMPLEMENTATION"
    VERIFICATION = "VERIFICATION"
    REPLAN = "REPLAN"
    CHECKPOINTING = "CHECKPOINTING"
    COMPLETE = "COMPLETE"
    STOPPED = "STOPPED"


class Status(StrEnum):
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    CHECKPOINT_READY = "CHECKPOINT_READY"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    STAGNATED = "STAGNATED"
    REPEATED_FAILURE = "REPEATED_FAILURE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    BLOCKED_EXTERNAL = "BLOCKED_EXTERNAL"
    UNSAFE_DEPENDENCY = "UNSAFE_DEPENDENCY"
    SCOPE_DRIFT = "SCOPE_DRIFT"
    INVALID_STATE = "INVALID_STATE"
    USER_CANCELLED = "USER_CANCELLED"


class CommandClass(StrEnum):
    READ_ONLY = "READ_ONLY"
    PROJECT_WRITE = "PROJECT_WRITE"
    GLOBAL_WRITE = "GLOBAL_WRITE"
    NETWORK_WRITE = "NETWORK_WRITE"
    SECRET_ACCESS = "SECRET_ACCESS"
    BILLABLE_ACTION = "BILLABLE_ACTION"
    PUBLICATION = "PUBLICATION"
    PRIVILEGED = "PRIVILEGED"


TERMINAL_STATUSES = {status for status in Status if status is not Status.RUNNING}
